### ISSUE TITLE
Why does user.type has "email" as format type?

### ISSUE THREAD

**Issue by thanpolas** [timberio/log-event-json-schema#46]
There is a user property named `type`, the full path is `context.user.type`, this property has the following schema definition:

```
type: {
    type: "string",
    description: "The type of user. Used in systems where there are multiple user types. This helps to     denote users in the case of polymorphism.",
    format: "email",
    minLength: 1,
    maxLength: 256
}
```

Why is the `format` set to `email` for this property?

**Comment by binarylogic** [comment]
Hi @thanpolas, this definitely should not be the case. Feel free to submit a PR that fixes it, otherwise we'll get a fix out early next week.
